Implements sub-menus [sitemap_pages child_of="current"] and [sitemap_pages child_of="1234"]
zedzedzed/table-of-contents-plus pull request #153
Opened 2023-08-25 07:29 UTC by flagsoft

Implements sub-menus [sitemap_pages child_of="current"] and [sitemap_pages child_of="1234"]
status:works with php 8.2 and WordPress 6.3

Just place 
  [sitemap_pages child_of="current"]
within a page to display sub-menu of current page.

Or
  [sitemap_pages child_of="1234"]
for sub-menus of a sub-menu, for example for footers.

2023-09-18 06:55 UTC, zedzedzed requested changes
Thanks for the PR, some comments added. Let me know if you need further detail.

2023-09-18 06:55 UTC, zedzedzed commented on class-toc-plus.php
> +					'child_of'     => $this->options['child_of']
`$this->options['child_of']` doesn't exist in the class's options property, so this can be

`'child_of' => 0`

2023-09-18 06:55 UTC, zedzedzed commented on class-toc-plus.php
> +
Please remove all debugs

2023-09-18 06:55 UTC, zedzedzed commented on class-toc-plus.php
> +
Don't need the final else statement (it's empty) and remove the commented out line.

2023-09-18 06:55 UTC, zedzedzed commented on class-toc-plus.php
> +				$args_child_of = $child_of;
`$child_of` shouldn't exist as we haven't used `extract()` from the shortcode attributes so this reference is incorrect? Use `$atts['child_of']` instead.

2023-09-18 06:55 UTC, zedzedzed commented on class-toc-plus.php
> +			$args_child_of = 0;
I think you can avoid using a new local var to store this. Just use `$atts['child_of']` where you can.

2023-09-18 08:57 UTC, flagsoft commented
I don't know how to proceed from this.

You can just use this on your test-site, and make changes if requried.
**But remember:**  The is_number is required (?) as far as I remember to differ between "1234" sub-menu as a page-id oder name "abc".

[sitemap_pages child_of="current"]  <- Use this for current page

[sitemap_pages child_of="1234"] <- Use this for a specific page id number

2023-09-19 00:17 UTC, zedzedzed approved these changes

2023-09-19 00:17 UTC, merged